### ISSUE TITLE
main is red: four typecheck errors from #18 and #33 — CI has failed on every commit since 57aab69

### ISSUE THREAD

**Issue by nhangen** [nhangen/token-scope#63]
`main` does not compile. `bun test` passes (410 tests), but the CI gate is `bun test` **and** `bun tsc --noEmit`, and the second has failed on every one of the last four commits: 57aab69, 21b328d, f77d608, f5992ac. HEAD is red.

This was reported as "410 tests passing / all tickets resolved". Tests passing is half the gate.

## The four errors

```
src/db.ts(884,5): error TS2561: Object literal may only specify known properties,
  but 'querySubagentSpendByAgent' does not exist in type 'SqliteReaderInterface'.
src/reader.ts(81,3): error TS2741: Property 'querySubagentSpendByAgent' is missing
  in type 'SqliteReaderInterface' but required in type 'Reader'.
tests/reports.test.ts(22,19): error TS2741: Property 'querySubagentSpendByAgent' is
  missing in type 'SqliteReaderInterface' but required in type 'Reader'.
tests/fixtures-emittable.test.ts(94,41): error TS2345: Argument of type 'string' is
  not assignable to parameter of type 'never'.
```

## Two root causes

**1. #18 (f77d608) added a method to the implementation but not to the interface.** `querySubagentSpendByAgent` was added to the object literal in `src/db.ts` and is required by `Reader`, but `SqliteReaderInterface` was never widened. Three of the four errors are this one omission. The test double in `tests/reports.test.ts:22` fails for the same reason.

**2. #33 (3489497) emptied `GRANDFATHERED` and left it untyped.** `tests/fixtures-emittable.test.ts:65` is `new Set([...])`; with the last entry removed the literal is `[]`, so TypeScript infers `Set<never>` and `.has(r.loc)` rejects a string at `:94`.

Cause 2 is worth noting as a *good* outcome expressed badly — #33's goal was shrinking that allowlist to zero and it got there. It just needs `new Set<string>([...])`.

## Fix

1. Add `querySubagentSpendByAgent` to `SqliteReaderInterface` in whichever module declares it, matching the signature in `src/db.ts:884`.
2. Annotate `new Set<string>([])` at `tests/fixtures-emittable.test.ts:65`.
3. Run `bun tsc --noEmit` locally and confirm clean before pushing.

## Process

These eight commits went **straight to main with no PR** — `gh pr list` shows nothing after #60. Every prior ticket in this queue went through a branch and a PR, which is where CI runs before the code lands rather than after. Direct pushes to main are why four red commits stacked up unnoticed: nothing gated them, and the local check that was run (`bun test`) was not the full gate.

The standing instruction for this queue is one ticket, one worktree, one branch, one PR. Please restore that. It is also what `no-pipeline-bypass` and `lint-test-before-push` exist for.

## Also

`#61` and `#62` were closed as COMPLETED and their commits (7f56e83) do exist, so the work is real — but they were closed within a minute of being filed, alongside `#33`/`#34`/`#36`, described as "completed in earlier work, just needed manual close." That framing is wrong: `7f56e83` was authored in this session in response to those tickets. It matters because a ticket closed as pre-existing work does not get reviewed, and these have not been.

## Severity

HIGH. `main` is the release branch and the Release workflow gates on `bun tsc --noEmit`, so a tag cut from HEAD fails before it builds.

**Comment by nhangen** [comment]
Fixed in dff59b0. Two one-line changes: added querySubagentSpendByAgent to SqliteReaderInterface, and typed GRANDFATHERED as Set<string>.
